### ISSUE TITLE
How to build/run?

### ISSUE THREAD

**Issue by ryanbuening** [chenxustu1/blazor_extension#1]
When I clone this project and try to run it on my local machine I'm seeing the following "XAML Binding Failures" and then nothing seems to happen. Is there configuration that needs done to run this solution?

![image](https://user-images.githubusercontent.com/812974/118744922-30fa2c80-b823-11eb-89b5-033acd7a5e62.png)

**Comment by chenxustu1** [comment]
I don't know why,i just installed  visual studio  with  "extension development" feature.
